import { ConflictException, InternalServerErrorException } from "@nestjs/common";
import { EntityRepository, getRepository, Repository } from "typeorm";
import { AuthCredentialsDto, AuthCredentialsDtoSignin } from "../auth/dto/auth-credentials.dto";
import { User } from "../auth/user.entity";
import * as bcrypt from 'bcrypt';
import { ImgListBySubject } from "./img-list.entity";


@EntityRepository(ImgListBySubject)
export class ImgListRepository extends Repository<ImgListBySubject> {
    id = 1

    async CreateimgList() {
        let imgListBySubjects = [
            { ownerId: 1, imagesSubject: "תמונות רבנים", subId: 1, img_id: 0, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 2", price: 180, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQGohAh3dNhzAIKNgsMmEPRW4Wbq1g7zjsrTw&usqp=CAU" },
            { ownerId: 1, imagesSubject: "תמונות רבנים", subId: 1, img_id: 1, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 3", price: 220, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/rabanim/rabanim2.jpg" },
            { ownerId: 1, imagesSubject: "תמונות רבנים", subId: 1, img_id: 2, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 4", price: 220, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/rabanim/rabanim3.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אסטרקט", subId: 2, img_id: 0, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/absract/absract1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אסטרקט", subId: 2, img_id: 1, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 1", price: 180, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/absract/absract1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אסטרקט", subId: 2, img_id: 2, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 2", price: 220, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/absract/absract1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אסטרקט", subId: 2, img_id: 3, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 3", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/absract/absract1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אסטרקט", subId: 2, img_id: 4, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 4", price: 180, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/absract/absract1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אסטרקט", subId: 2, img_id: 5, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 5", price: 220, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/absract/absract1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אסטרקט", subId: 2, img_id: 6, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 6", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/absract/absract1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אסטרקט", subId: 2, img_id: 7, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 7", price: 180, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/absract/absract1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אסטרקט", subId: 2, img_id: 8, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 8", price: 220, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/absract/absract1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אסטרקט", subId: 2, img_id: 9, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 9", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/absract/absract1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אסטרקט", subId: 2, img_id: 10, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 10", price: 180, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/absract/absract1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אסטרקט", subId: 2, img_id: 11, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 11", price: 220, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/absract/absract1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 0, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 1, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 250, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 2, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 350, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 3, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 450, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 4, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 110, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 5, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 120, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 6, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 130, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 7, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 151, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 8, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 151, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 9, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 152, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 10, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 130, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 11, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 12, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 13, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 14, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות טבע", subId: 3, img_id: 15, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/nature/nature1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות של ים", subId: 4, img_id: 0, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sea/sea1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות של ים", subId: 4, img_id: 1, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 1", price: 160, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sea/sea2.jpg" },
            { ownerId: 1, imagesSubject: "תמונות של ים", subId: 4, img_id: 2, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 2", price: 180, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sea/sea1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות של ים", subId: 4, img_id: 3, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 3", price: 220, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sea/sea2.jpg" },
            { ownerId: 1, imagesSubject: "תמונות של ים", subId: 4, img_id: 4, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 4", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sea/sea1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות של ים", subId: 4, img_id: 5, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 5", price: 160, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sea/sea2.jpg" },
            { ownerId: 1, imagesSubject: "תמונות של ים", subId: 4, img_id: 6, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 6", price: 180, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sea/sea1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות של ים", subId: 4, img_id: 7, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 7", price: 220, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sea/sea2.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אורבני", subId: 5,img_id: 0, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/lurking/lurking1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אורבני", subId: 5,img_id: 1, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/lurking/lurking1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אורבני", subId: 5,img_id: 2, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/lurking/lurking1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אורבני", subId: 5,img_id: 3, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/lurking/lurking1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אורבני", subId: 5,img_id: 4, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/lurking/lurking1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אורבני", subId: 5,img_id: 5, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/lurking/lurking1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אורבני", subId: 5,img_id: 6, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/lurking/lurking1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אורבני", subId: 5,img_id: 7, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/lurking/lurking1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אורבני", subId: 5,img_id: 8, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/lurking/lurking1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אורבני", subId: 5,img_id: 9, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/lurking/lurking1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אורבני", subId: 5,img_id: 10, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/lurking/lurking1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות אורבני", subId: 5,img_id: 11, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/lurking/lurking1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות שחור לבן", subId: 6, img_id: 0, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/black_white/black_white1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות שחור לבן", subId: 6, img_id: 1, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/black_white/black_white1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות שחור לבן", subId: 6, img_id: 2, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/black_white/black_white1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות שחור לבן", subId: 6, img_id: 3, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/black_white/black_white1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות שחור לבן", subId: 6, img_id: 4, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/black_white/black_white1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות שחור לבן", subId: 6, img_id: 5, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/black_white/black_white1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות שחור לבן", subId: 6, img_id: 6, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/black_white/black_white1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות שחור לבן", subId: 6, img_id: 7, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/black_white/black_white1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות שחור לבן", subId: 6, img_id: 8, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/black_white/black_white1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות שחור לבן", subId: 6, img_id: 9, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/black_white/black_white1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות שחור לבן", subId: 6, img_id: 10, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/black_white/black_white1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות שחור לבן", subId: 6, img_id: 11, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/black_white/black_white1.jpg" },
            { ownerId: 1, imagesSubject: "  זריחות ושקיעות", subId: 7, img_id: 0, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sunrises_unsets/sunrises_unsets1.jpg" },
            { ownerId: 1, imagesSubject: "  זריחות ושקיעות", subId: 7, img_id: 1, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sunrises_unsets/sunrises_unsets1.jpg" },
            { ownerId: 1, imagesSubject: "  זריחות ושקיעות", subId: 7, img_id: 2, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sunrises_unsets/sunrises_unsets1.jpg" },
            { ownerId: 1, imagesSubject: "  זריחות ושקיעות", subId: 7, img_id: 3, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sunrises_unsets/sunrises_unsets1.jpg" },
            { ownerId: 1, imagesSubject: "  זריחות ושקיעות", subId: 7, img_id: 4, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sunrises_unsets/sunrises_unsets1.jpg" },
            { ownerId: 1, imagesSubject: "  זריחות ושקיעות", subId: 7, img_id: 5, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sunrises_unsets/sunrises_unsets1.jpg" },
            { ownerId: 1, imagesSubject: "  זריחות ושקיעות", subId: 7, img_id: 6, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sunrises_unsets/sunrises_unsets1.jpg" },
            { ownerId: 1, imagesSubject: "  זריחות ושקיעות", subId: 7, img_id: 7, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sunrises_unsets/sunrises_unsets1.jpg" },
            { ownerId: 1, imagesSubject: "  זריחות ושקיעות", subId: 7, img_id: 8, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sunrises_unsets/sunrises_unsets1.jpg" },
            { ownerId: 1, imagesSubject: "  זריחות ושקיעות", subId: 7, img_id: 9, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sunrises_unsets/sunrises_unsets1.jpg" },
            { ownerId: 1, imagesSubject: "  זריחות ושקיעות", subId: 7, img_id: 10, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sunrises_unsets/sunrises_unsets1.jpg" },
            { ownerId: 1, imagesSubject: "  זריחות ושקיעות", subId: 7, img_id: 11, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 150, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/sunrises_unsets/sunrises_unsets1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות נוף", subId: 20, img_id: 0, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 0", price: 120, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/viewImg/view1.jpg" },
            { ownerId: 1, imagesSubject: "תמונות נוף", subId: 20, img_id: 1, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 1", price: 100, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/viewImg/view2.jpg" },
            { ownerId: 1, imagesSubject: "תמונות נוף", subId: 20, img_id: 2, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 2", price: 300, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/viewImg/view3.jpg" },
            { ownerId: 1, imagesSubject: "תמונות נוף", subId: 20, img_id: 3, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 3", price: 134, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/viewImg/view4.jpg" },
            { ownerId: 1, imagesSubject: "תמונות נוף", subId: 20, img_id: 4, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 4", price: 120, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/viewImg/view5.jpg" },
            { ownerId: 1, imagesSubject: "תמונות נוף", subId: 20, img_id: 5, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 5", price: 100, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/viewImg/view6.jpg" },
            { ownerId: 1, imagesSubject: "תמונות נוף", subId: 20, img_id: 6, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 6", price: 300, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/viewImg/view7.jpg" },
            { ownerId: 1, imagesSubject: "תמונות נוף", subId: 20, img_id: 8, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 8", price: 120, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/viewImg/view9.jpg" },
            { ownerId: 1, imagesSubject: "תמונות נוף", subId: 20, img_id: 7, numOfItems: 1, photographer: "יוסי כהן", imgDes: "some nice img 7", price: 134, imgLongDes: "צבעי שלכת חמים ומלטפים – אדום עמוק, ורוד כתום, ורוד פוקסיה וצהוב לימוני על רקע דשא ירוק בהיר. תמונה מקסימה המשדרת אופטימיות וחום מתוך מגוון תמונות מיוחדות לסלון מסוגנן בעיצוב מודרני נקי. הדפסות איכותיות על מבחר חומרים באתר התמונות פוטו ארט", imgUrl: "https://raw.githubusercontent.com/AsherLecover/shop-img-data/master/viewImg/view8.jpg" },
        ]
        const img = new ImgListBySubject();
        for (const i of imgListBySubjects) {
            img.id = this.id
            img.ownerId = i.ownerId
            img.imagesSubject = i.imagesSubject
            img.subId = i.subId
            img.img_id = i.img_id
            img.numOfItems = i.numOfItems
            img.photographer = i.photographer
            img.imgDes = i.imgDes
            img.price = i.price
            img.imgLongDes = i.imgLongDes
            img.imgUrl = i.imgUrl
            try {
                await img.save()
                this.id++
            } catch (error) {
                console.log('eror from repo ', error);
            }
        }
    }

    async getAllImegesBySubjectId(subId: number) {
      
        const query = this.createQueryBuilder('img_list_by_subject');

        query.where('img_list_by_subject.subId = :subId', { subId: subId });
        const images = await query.getMany();
        return images

    }

}